DaiLapuDrug.Web/Areas/Admin/Models/OptionViewModel.cs
using DaiLapuDrug.Web.Data.Entities;

namespace DaiLapuDrug.Web.Areas.Admin.Models
{
    public class OptionViewModel
    {
        public int Id { get; set; }

        public EOptionType Type { get; set; }

        public string Value { get; set; }
    }
}

DaiLapuDrug.Web/Areas/Admin/Controllers/OptionsController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using DaiLapuDrug.Web.Areas.Admin.Models;
using DaiLapuDrug.Web.Data;
using DaiLapuDrug.Web.Data.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DaiLapuDrug.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OptionsController : Controller
    {
        private readonly IMapper mapper;
        private readonly ApplicationDbContext applicationDbContext;

        public OptionsController(IMapper mapper, ApplicationDbContext applicationDbContext)
        {
            this.mapper = mapper;
            this.applicationDbContext = applicationDbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Edit(EOptionType type)
        {
            var options = applicationDbContext.Options
                .Where(x => x.Type == type)
                .ProjectTo<OptionViewModel>(mapper.ConfigurationProvider)
                .ToList();

            var viewModel = new EditOptionsViewModel()
            {
                Options = options,
                Type = type,
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(EditOptionsViewModel model)
        {
            model.Options = model.Options.Where(x => x != null).ToList();

            var options = applicationDbContext.Options
                .Where(x => x.Type == model.Type)
                .ToList();

            // added
            foreach (var option in model.Options.Where(x => x.Id == 0))
            {
                var newOption = mapper.Map<Option>(option);
                newOption.Type = model.Type;
                applicationDbContext.Options.Add(newOption);
            }

            // updated
            foreach (var option in model.Options.Where(x => x.Id != 0))
            {
                var oldOption = options.FirstOrDefault(x => x.Id == option.Id);
                if (option.Value != oldOption.Value)
                {
                    oldOption.Value = option.Value;

                    applicationDbContext.Update(oldOption);
                }
            }

            // deleted
            foreach (var option in options)
            {
                if (!model.Options.Any(x => x.Id == option.Id))
                {
                    applicationDbContext.Options.Remove(option);
                }
            }

            applicationDbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult GetOptionPartialView()
        {
            return PartialView("_OptionItem", new OptionViewModel());
        }
    }
}

DaiLapuDrug.Web/Areas/Admin/Views/Options/Edit.cshtml
@model EditOptionsViewModel

<form asp-action="Edit" asp-controller="Options" asp-area="Admin">
    <input asp-for="Type" type="hidden" />

    <div class="row">
        <div class="col-12 col-md-3">
            <div class="row" id="options_container">
                @foreach (var item in Model.Options)
                {
                    @await Html.PartialAsync("_OptionItem", item);
                }
            </div>

        </div>

    </div>
    <a href="javascript:0" onclick="addNewItem()" class="btn btn-primary">Add new item</a>
    <input type="submit" class="btn btn-primary" value="Submit" />
</form>

<script>
    function addNewItem() {
        $.get('@Url.Action("GetOptionPartialView", "Options", new { Area = "Admin" })', function (data) {
            $('#options_container').append(data);
        });
    }
</script>

DaiLapuDrug.Web/Areas/Admin/Views/Options/Index.cshtml
<a href="@Url.Action("Edit", "Options", new { area = "Admin", type = (int)EOptionType.PetType })">Типы питомцев</a>
<a href="@Url.Action("Edit", "Options", new { area = "Admin", type = (int)EOptionType.PetSubType })">Подтипы</a>
<a href="@Url.Action("Edit", "Options", new { area = "Admin", type = (int)EOptionType.PetBreed })">Порода</a>
<a href="@Url.Action("Edit", "Options", new { area = "Admin", type = (int)EOptionType.PetColor })">Окрас</a>
<a href="@Url.Action("Edit", "Options", new { area = "Admin", type = (int)EOptionType.PetHairType })">Тип шерсти</a>
<a href="@Url.Action("Edit", "Options", new { area = "Admin", type = (int)EOptionType.PetPersonality })">Особенности характера</a>
<a href="@Url.Action("Edit", "Options", new { area = "Admin", type = (int)EOptionType.PetSize })">Размер</a>
<a href="@Url.Action("Edit", "Options", new { area = "Admin", type = (int)EOptionType.PetStatus })">Статус</a>

DaiLapuDrug.Web/Areas/Admin/Views/Options/_OptionItem.cshtml
@model OptionViewModel

@using (Html.BeginCollectionItem("Options"))
{
    <div class="form-group col-12">
        <input asp-for="Id" type="hidden" />
        <input asp-for="Value" type="text" class="form-control"/>
        <a href="javascript:0" onclick="$(this).parent().remove()">Remove</a>
    </div>               
}