DaiLapuDrug.Web/Areas/Admin/Models/ArticleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DaiLapuDrug.Web.Areas.Admin.Models
{
    public class ArticleViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string PreviewPicture { get; set; }

        public string PreviewBody { get; set; }
        public bool IsPublished { get; set; } 
        public int? PetId { get; set; }
    }
}

DaiLapuDrug.Web/Areas/Admin/Controllers/ArticlesController.cs
using AutoMapper;
using DaiLapuDrug.Web.Areas.Admin.Models;
using DaiLapuDrug.Web.Data;
using DaiLapuDrug.Web.Data.Entities;
using DaiLapuDrug.Web.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DaiLapuDrug.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ArticlesController : Controller
    {
        private readonly IMapper mapper;
        private readonly ApplicationDbContext applicationDbContext;
        private readonly FileAttachmentService fileAttachmentService;
        private readonly AzureBlobStorageService azureBlobStorageService;

        public ArticlesController(IMapper mapper, ApplicationDbContext applicationDbContext, 
            FileAttachmentService fileAttachmentService, AzureBlobStorageService azureBlobStorageService)
        {
            this.mapper = mapper;
            this.applicationDbContext = applicationDbContext;
            this.fileAttachmentService = fileAttachmentService;
            this.azureBlobStorageService = azureBlobStorageService;
        }

        public IActionResult Index()
        {
            var articles = applicationDbContext.Articles.Where(x => x.IsDeleted == false && x.PetId == null)
                .Select(x => new ArticleViewModel()
                {
                    Id = x.Id,
                    Title = x.Title,
                    Body = x.Body,
                    PetId = x.PetId,
                    IsPublished = x.IsPublished,
                });

            return View(articles);
        }

        public IActionResult Create(int? petId = null)
        {
            var viewModel = new ArticleViewModel()
            {
                PetId = petId,
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ArticleViewModel model)
        {
            var article = mapper.Map<Article>(model);

            article.CreatedAt = DateTime.Now;
            article.Slug = SlugGenerator.SlugGenerator.GenerateSlug(article.Title);

            applicationDbContext.Articles.Add(article);
            applicationDbContext.SaveChanges();

            if (model.PetId != null)
            {
                return RedirectToAction("Edit", "Pets", new { id = model.PetId });
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var article = applicationDbContext.Articles.FirstOrDefault(x => x.Id == id);

            if (article == null)
            {
                return NotFound();
            }

            var viewModel = mapper.Map<ArticleViewModel>(article);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ArticleViewModel model)
        {
            var article = applicationDbContext.Articles.FirstOrDefault(x => x.Id == model.Id);

            if (article == null)
            {
                return NotFound();
            }

            mapper.Map(model, article);

            article.UpdatedAt = DateTime.Now;
            article.Slug = SlugGenerator.SlugGenerator.GenerateSlug(article.Title);

            applicationDbContext.Articles.Update(article);
            applicationDbContext.SaveChanges();

            if (model.PetId != null)
            {
                return RedirectToAction("Edit", "Pets", new { id = model.PetId });
            }

            return RedirectToAction(nameof(Index));
        }

        public ActionResult Delete(int id)
        {
            var article = applicationDbContext.Articles.FirstOrDefault(x => x.Id == id);

            if (article == null)
            {
                return NotFound();
            }

            var viewModel = mapper.Map<ArticleViewModel>(article);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(ArticleViewModel model)
        {
            var article = applicationDbContext.Articles.FirstOrDefault(x => x.Id == model.Id);

            if (article == null)
            {
                return NotFound();
            }

            article.DeletedAt = DateTime.Now;
            article.IsDeleted = true;

            applicationDbContext.Update(article);
            applicationDbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        public async Task<ActionResult> UploadArticleFileAttachments(int articleId)
        {
            var attachments = await fileAttachmentService.UploadFromRequestForm("articles");

            foreach (var attachment in attachments)
            {
                var articleFileAttachment = new ArticleFileAttachment()
                {
                    FileAttachment = attachment,
                    ArticleId = articleId,
                };

                applicationDbContext.ArticleFileAttachments.Add(articleFileAttachment);
            }

            await applicationDbContext.SaveChangesAsync();

            List<string> uris = new List<string>();

            foreach (var attachment in attachments)
            {
                var attachmentUri = await azureBlobStorageService.GetBlobUri("articles", attachment.BlobName);
                uris.Add(attachmentUri.ToString());
            }

            var result = new
            {
                Urls = uris
            };

            return Json(result);
        }
    }
}

DaiLapuDrug.Web/Controllers/NewsletterController.cs
using MailChimp;
using MailChimp.Net;
using MailChimp.Net.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DaiLapuDrug.Web.Controllers
{
    public class NewsletterController : Controller
    {
        private readonly MailChimpManager mailChimpManager;

        public NewsletterController(MailChimpManager mailChimpManager)
        {
            this.mailChimpManager = mailChimpManager;
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Subscribe(string email)
        {
            var lists = await mailChimpManager.Lists.GetAllAsync();
            var defaultList = lists.FirstOrDefault(x => x.Name == "Day Lapu Drug");

            if (defaultList == null)
                throw new Exception("Default Mail list not found");

            var member = new Member
            {
                EmailAddress = email,
                StatusIfNew = Status.Subscribed
            };

            await mailChimpManager.Members.AddOrUpdateAsync(defaultList.Id, member);

            return new EmptyResult();
        }
    }
}

DaiLapuDrug.Web/Areas/Admin/Views/Articles/Create.cshtml
@model ArticleViewModel

@{
    if (Model.PetId == null)
    {
        ViewBag.Title = "Create article";
    }
    else
    {
        ViewBag.Title = "Create pet post";
    }
}

<h3>@ViewBag.Title</h3>

<form asp-action="Create" asp-controller="Articles" asp-area="Admin">
    <input type="hidden" asp-for="Id" />

    <partial name="_Item" model="Model">
</form>

DaiLapuDrug.Web/Areas/Admin/Views/Articles/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

DaiLapuDrug.Web/Areas/Admin/Views/Articles/Edit.cshtml
@model ArticleViewModel

@{
    ViewBag.Title = "Редактировать новость/статью";
}

<form asp-action="CreateArticleCampaign" asp-controller="Newsletter" asp-area="Admin">
    <input type="hidden" name="articleId" value="@Model.Id" />
    <input type="submit" class="btn btn-primary" value="Создать новостную кампанию" />
</form>

<h3>@ViewBag.Title</h3>


<form asp-action="Edit" asp-controller="Articles" asp-area="Admin">
    <input type="hidden" asp-for="Id" />

    <partial name="_Item" model="Model">
</form>

DaiLapuDrug.Web/Areas/Admin/Views/Articles/Index.cshtml
@model IQueryable<ArticleViewModel>

<div class="mb-5">
    <a href="@Url.Action("Create", "Articles", new { Area = "Admin" })" class="btn btn-primary">Create new</a>
</div>

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add().Titled("Title").Encoded(false).RenderedAs(model => new HtmlString($"<a href=\"" + Url.Action("Edit", "Articles", new { id = model.Id, Area = "Admin" }) + "\">" + model.Title + "</a>"));
    })
    .Empty("No data found")
    .Pageable()
)

DaiLapuDrug.Web/Areas/Admin/Views/Articles/_Item.cshtml
@model ArticleViewModel

<style>

</style>

<div class="row">
    <div class="col-6">
        <div class="row">
            <div class="form-group col-12">
                <input asp-for="IsPublished" type="checkbox" />
                <label asp-for="IsPublished" class="control-label">Опубликована?</label>
            </div>

            <input type="hidden" asp-for="PetId" />

            @if (Model.PetId == null)
            {
                <div class="form-group col-12">
                    <label asp-for="Title" class="control-label">Заголовок</label>
                    <input asp-for="Title" type="text" class="form-control" />
                    @Html.ValidationMessageFor(x => x.Title, "", new { @class = "text-danger" })
                </div>
            }
        </div>
    </div>
    <div class="col-12">
        <div class="form-group">
            <label asp-for="Body" class="control-label">Содержание</label>
            <textarea asp-for="Body" type="text" class="form-control html-editor" style="min-height: 1000px"></textarea>
        </div>
    </div>
    @if (Model.PetId == null)
    {
        <div class="form-group col-12">
            <label asp-for="PreviewBody" class="control-label">Текст превью</label>
            <input asp-for="PreviewBody" type="text" class="form-control" />
            @Html.ValidationMessageFor(x => x.PreviewBody, "", new { @class = "text-danger" })
        </div>
    }
    <div class="col-12">
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit" />
        </div>
    </div>
</div>

<script>
    function getImageUploadHandler() {
        return '@Url.Action("UploadArticleFileAttachments", "Articles", new { area = "Admin", articleId = Model.Id })'
    }
</script>